### PR TITLE
Built in logos

### LINKED ISSUE #6: Add Youtuber Logos
image

### PR DESCRIPTION
**Pull request by Fish1**
Feature: Added logos for youtubers to the bottom right of the graphs. Only RedEagle and LTE for now, we can add more later. And probably add a custom logo import feature.

Code: Control the chart positioning & size via the page. The style modal will control the logo store, and the the page will render the image in the logo store.

image

image

closes #6

### CODE REVIEW

**Comment by Flizzyclone** [comment]
This looks good, just one issue. When changing between chart positions, the sizing is thrown off. 
image

This is because setting width in logoSize to undefined doesn't actually change the style of the element. So the element ends up w/ width:100% and height:100%
image

If you set to 'auto' instead of undefined, you get desired behavior.
```
let logoSize: { width: string; height: string } = {
	width: '100%',
	height: '100%'
};

$: if ($ChartPositionStore === 'bottom' && $ChartTypeStore !== 'battle') {
	logoSize = { width: 'auto', height: '50%' };
} else if ($ChartPositionStore === 'bottom' && $ChartTypeStore === 'battle') {
	logoSize = { width: 'auto', height: '100%' };
} else if ($ChartPositionStore === 'left' && $ChartTypeStore !== 'battle') {
	logoSize = { width: '50%', height: 'auto' };
} else if ($ChartPositionStore === 'left' && $ChartTypeStore === 'battle') {
	logoSize = { width: '100%', height: 'auto' };
}
```

**Review by Flizzyclone — CHANGES_REQUESTED** [review]
See above

**Comment by Fish1** [comment]
> This looks good, just one issue. When changing between chart positions, the sizing is thrown off. image
> 
> This is because setting width in logoSize to undefined doesn't actually change the style of the element. So the element ends up w/ width:100% and height:100% image
> 
> If you set to 'auto' instead of undefined, you get desired behavior.
> 
> ```
> let logoSize: { width: string; height: string } = {
> 	width: '100%',
> 	height: '100%'
> };
> 
> $: if ($ChartPositionStore === 'bottom' && $ChartTypeStore !== 'battle') {
> 	logoSize = { width: 'auto', height: '50%' };
> } else if ($ChartPositionStore === 'bottom' && $ChartTypeStore === 'battle') {
> 	logoSize = { width: 'auto', height: '100%' };
> } else if ($ChartPositionStore === 'left' && $ChartTypeStore !== 'battle') {
> 	logoSize = { width: '50%', height: 'auto' };
> } else if ($ChartPositionStore === 'left' && $ChartTypeStore === 'battle') {
> 	logoSize = { width: '100%', height: 'auto' };
> }
> ```

What web browser are you on? I've tried firefox & chromium on linux, and firefox on windows.

**Comment by Fish1** [comment]
Just tried it on windows chrome and wasn't able to replicate the issue. Are you on a Mac?

**Comment by Flizzyclone** [comment]
I am on Windows 11, latest Chrome. This happened on Firefox and Edge as well. Perhaps I did not describe what I did clearly enough, here is a GIF:

yapmsLogoSizing

**Comment by Fish1** [comment]
I cannot replicate it, every thing seems to be working for me. I'll change it to auto anyways.

**Comment by Flizzyclone** [comment]
is working perfectly on my end now

**Review by Flizzyclone — APPROVED** [review]

**Pull request merged**
