### PR TITLE
U.S State Legislative Maps

### PR DESCRIPTION
**Pull request by Flizzyclone**
This PR adds state legislative maps for USA states. Maps are organized into upper house & lower house. All maps are sourced from the Census bureau nationwide files ([upper](https://www2.census.gov/geo/tiger/GENZ2022/shp/cb_2022_us_sldu_500k.zip), [lower](https://www2.census.gov/geo/tiger/GENZ2022/shp/cb_2022_us_sldl_500k.zip)) and then filtered.

Pictures are from [Pexels (lower)](https://www.pexels.com/photo/the-california-state-capitol-building-under-a-blue-clear-sky-8347375/) & [Pixabay (upper)](https://pixabay.com/photos/salt-lake-city-capitol-capital-1659141/)

### CODE REVIEW

**Comment by Fish1** [comment]
Wow Nice! I'll try to get this in tomorrow morning!

**Review by Fish1 — CHANGES_REQUESTED** [review]
The maps looks great!

I think the _state should be removed from the country identifier.

I think if you'd like to make it more apparent that its the state legislature, then you could maybe say virginia_house & virginia_senate or something.

But I think all the USA maps should be under the same path.

**Comment by Fish1** [comment]
Also, for the original-source JSON needs to have double quotes. You should be able to single quote the original-source, or use the $quot; entity like you are in the candiates array.

**Comment by Flizzyclone** [comment]
original-source has been single quoted & country identifer changed (i left maps in usa_state folder for organization). Please re-review

**Review by Fish1 — APPROVED** [review]
LGTM

**Pull request merged**
