### PR TITLE
Fix counties (for real)! and add dev warning for duplicate region IDs

### LINKED ISSUE #522: Virginia's counties don't work.
When I click on a county in Virginia, a county in Maryland changes instead of the one I'm clicking on.

### PR DESCRIPTION
**Pull request by Flizzyclone**
This PR fixes the last problem with the new counties map and adds a warning on region load for duplicate region IDs so we can hopefully avoid and at least easily debug this in the future. Checking for duplicates runs only in a dev environment to avoid running costly array logic every time a map is loaded.

### CODE REVIEW

**Review by Fish1 — CHANGES_REQUESTED** [review]
Little bit of a nit pick, since this code only runs in dev.

But could you use a map instead of an array here? For constant time lookup.

**Comment by Flizzyclone** [comment]
good point, will fix in a bit here

**Comment by Flizzyclone** [comment]
oh fixes #522 btw

**Review by Fish1 — APPROVED** [review]
LGTM

**Pull request merged**
