### PR TITLE
Button fixes

### LINKED ISSUE #87: 'Home' Button doesn't work
When in app, the Home button doesn't redirect.

### LINKED ISSUE #88: Clicking anywhere on home social buttons does not work
Due to an improperly placed <a>, only clicking on text for the social buttons on the home page redirects you properly. This is fixed on other buttons.

### PR DESCRIPTION
**Pull request by Flizzyclone**
Fixes both the home button not redirecting and buttons on the home page only working when you click on text. Also fixes home page button wrapping issues identified in the Home Page PR.

Summary of code changes
- Switches the structure of home social buttons to have the <a> completely wrapping the element instead of the <a> inside the button.
- Makes home social buttons nowrap, fixing wrapping issues.
- Wraps the "Home" button on the app page in an <a> redirecting to "/".

Closes #87 and #88

### CODE REVIEW

**Review by Fish1 — CHANGES_REQUESTED** [review]
Looking at the buttons more, I think we can clean it up a bit by removing the button component. And just give the <a> tag the button styling. (for the navbar and social links)

Also, when possible, the parent element should control the positioning & size of the child elements. This makes it much easier to turn the children into their own components and be used in other places.

For example, in the future we might wanna make the social link buttons into their own components. If they have the 45% width, then wherever we put them, they are forced at 45% width. But with these changes, we can put them in other places cand control their widths and layout via a parent component.

EDIT: (the discord flex-wrap should be flex-nowrap)

image

**Comment by Flizzyclone** [comment]
Good catch, this is helped by the nowrap. Before without percentages they would wrap undesirably, hence the 45%. Good idea with the <a> replacing <button> as well. I will change

**Comment by Flizzyclone** [comment]
Replaced all buttons with <a>'s in them to just be <a>'s. Please re-review

**Review by Fish1 — APPROVED** [review]
LGTM

**Pull request merged**
