### PR TITLE
Home Page Updates

### LINKED ISSUE #141: MoreMapsModal rework
Currently the MoreMapsModal reads from a json file called MapList.json. Now that we are using Titles.json for map search, I am going to update the MoreMapsModal to use Titles.json as well filtering based on path.

### PR DESCRIPTION
**Pull request by Flizzyclone**
This PR adds a Historical Maps category to the home page, and fixes a visual issue with the search bar caused by daisyUI 3.0.

Summary of code changes:
- Adds a Historical Maps category to the home page. 
  - MoreMapsModal PR will place historical maps there
- Reorders Titles.json
- Adds an icon and property to selection cards for image attribution
  - All images used remain in the public domain (CC0)
- Adds border-gray-500 to the search bar

### CODE REVIEW

**Comment by Fish1** [comment]
What is the reason for the usahistorical route being added?

I feel like the /usa/house/1992 route described what the map is. If the point is to differentiate between filled-in maps and blank maps, then maybe we can do /usa/blank-house/1992 or something.

This way all the usa maps are under the same route, it's just the name of the map that changes.

**Comment by Flizzyclone** [comment]
Was mainly to differentiate for doing map search in the modal. Thinking back on it, I should add some logic to the definition of the modal that allows for searches before a specific year. I will do that and request re-review.

**Comment by Fish1** [comment]
@Flizzyclone before you add that feature, could you instead just revert the names of the maps back to what they were. Then make another PR for the feature you're talking about. It's just easier for me to review smaller PRs.

Just in general it's easier for me to review PRs that are about changing a single thing, instead of general PRs that do a lot of different things.

**Comment by Flizzyclone** [comment]
@Fish1 

That is what I'm going to do, but the functionality I'm talking about would be part of reworking MoreMapsModal. I can split that rework into a separate PR if you would like.

**Comment by Fish1** [comment]
If you want, you can keep it all on this PR. I know im probably also guilty of making big PRs, feel free too tell me if they are too big.

But like each of the bullets on this PR could be its own PR, or maybe combine two of them if they are very related.

**Comment by Flizzyclone** [comment]
Yeah that's fair. I will break it into a seperate PR.

**Comment by Flizzyclone** [comment]
Alright all MoreMapsModal changes removed. This should be a lot more manageable now.

**Review by Fish1 — APPROVED** [review]
LGTM

**Pull request merged**
